<a href="https://colab.research.google.com/github/Dakshak-Data/python_p/blob/main/Numpycamp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#What is numpy?
###NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional
#array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on
#arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra,
#basic statistical operations, random simulation and much more.

#At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

In [ ]:
#Numpy Arrays Vs Python Sequences
#NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an
#ndarray will create a new array and delete the original.

#The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

#NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such
#operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

#A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support
3Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [ ]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
# np.arange strike
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# with reshape row column
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
# np.ones and np.zeros deeplearning weights to return value fast
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

In [ ]:
# np.random fast
np.random.random((3,4))

array([[0.25735045, 0.97119883, 0.10703398, 0.44631996],
       [0.9025255 , 0.94498929, 0.68672335, 0.52313802],
       [0.19717231, 0.67994068, 0.29731739, 0.70113019]])

In [ ]:
# np.linspace lowernupper range give range equal disrtance points generete to find distance
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
# np.identitydiagonal item same
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a1 = np.arange(10,dtype=np.int32)  #atributes5
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim dimension say
a3.ndim

3

In [ ]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# itemsize
a3.itemsize

8

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


In [ ]:
#Changing Datatype

In [ ]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [ ]:
#Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2
#This section of code demonstrates how to create NumPy arrays using the arange function and then change their dimensions using the reshape method.

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# scalar operations a1 2 vector

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# relational operator <>/*
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [ ]:
#Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1
#The np.round() function in NumPy is used to round elements of an array to a specified number of decimal places. By default, if no number of decimal places is specified, it rounds to the nearest integer.

array([[ 6., 26., 87.],
       [91.,  0., 21.],
       [55., 87., 62.]])

In [ ]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([ 30030.,      0., 113274.])

In [ ]:
# mean/median/std/varaxis=0 refers to the columns, and axis=1 refers to the rows.
np.var(a1,axis=1)

array([1186.88888889, 1513.55555556,  188.66666667])

In [ ]:
# trigonomoetric functions
np.sin(a1)

array([[-0.2794155 ,  0.76255845, -0.82181784],
       [ 0.10598751,  0.        ,  0.83665564],
       [-0.99975517, -0.82181784, -0.7391807 ]])

In [ ]:
# dot product same toh he dot product hoga 1column and 2 row should be match
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents
np.exp(a1)

array([[4.03428793e+02, 1.95729609e+11, 6.07603023e+37],
       [3.31740010e+39, 1.00000000e+00, 1.31881573e+09],
       [7.69478527e+23, 6.07603023e+37, 8.43835667e+26]])

In [ ]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[36., 58., 64.],
       [10., 57., 93.]])

In [ ]:
import numpy as np

# Create a NumPy array with some floating-point numbers
my_array = np.array([1.2, -2.8, 3.5, 4.0, -5.1])

# Apply the np.ceil() function to find the ceiling of each element
ceiling_array = np.ceil(my_array)

# Print the original and the resulting array
print("Original array:", my_array)
print("Ceiling of the array:", ceiling_array)

Original array: [ 1.2 -2.8  3.5  4.  -5.1]
Ceiling of the array: [ 2. -2.  4.  4. -5.]


In [ ]:
import numpy as np

# Create a NumPy array with some floating-point numbers
my_array = np.array([1.2, 2.8, 3.5, 4.0, -5.1])

# Apply the np.floor() function to find the floor of each element
floor_array = np.floor(my_array)

# Print the original and the resulting array
print("Original array:", my_array)
print("Floor of the array:", floor_array)
#np.ceil() finds the "ceiling" above the number.
#np.floor() finds the "floor" below the number.
#np.round() finds the closest integer.

Original array: [ 1.2  2.8  3.5  4.  -5.1]
Floor of the array: [ 1.  2.  3.  4. -6.]


In [ ]:
#Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,0]

np.int64(4)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

np.int64(5)

In [ ]:
a3[1,1,0]

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5]

array([2, 3, 4])

In [ ]:
a2

In [ ]:
a2[0:2,1::2]

In [ ]:
a2[::2,1::2]

In [ ]:
a2[1,::3]

In [ ]:
a2[0,:]

In [ ]:
a2[:,2]

In [ ]:
a2[1:,1:3]

In [ ]:
import numpy as np
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[2,1:,1:]

In [ ]:
#Iterating

In [ ]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

In [ ]:
for i in a2:
  print(i)

In [ ]:
a3

In [ ]:
for i in a3:
  print(i)

In [ ]:
for i in np.nditer(a3):
  print(i)

In [ ]:
#Reshaping



In [ ]:
# Transpose colum to row swap
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel  3d to 1d array
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
#Stacking

In [ ]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hstack((a4,a5)) #horizontally combine

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical stacking vertically combined
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#Splitting

In [ ]:
# horizontal splitting
a4

In [ ]:
np.hsplit(a4,5)

In [ ]:
# vertical splitting

In [ ]:
np.vsplit(a5,2)

ValueError: array split does not result in an equal division