<a href="https://colab.research.google.com/github/Dakshak-Data/python_p/blob/main/NUMPYADVANCECAMP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy array vs Python lists#

In [ ]:
# speed
# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time

start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)

8.770409345626831


In [ ]:
# numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

1.5432665348052979


In [ ]:
3.26/0.06

In [ ]:
# memory
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [ ]:
a = np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)

In [ ]:
# convenience

In [ ]:
## Normal Indexing and slicing

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[1,2]

np.int64(6)

In [ ]:
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
# Fancy Indexing

a[:,[0,2,3]]

a[[0,2,3]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# Boolean Indexing
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[56, 17, 82, 53],
       [46,  5, 99, 93],
       [31, 78, 78, 56],
       [79, 25, 74, 75],
       [44, 31, 70, 69],
       [87, 92, 88, 26]])

In [ ]:
# find all numbers greater than 50
a[a > 50]

array([70, 64, 81, 82, 58, 99, 87, 96, 72, 92, 85, 79, 66, 66, 97])

In [ ]:
# find out even numbers
a[a % 2 == 0]

array([70, 64, 10, 82, 10, 12, 58, 28, 96, 72, 92, 66, 66, 46,  6])

In [ ]:
# find all numbers greater than 50 and are even

a[(a > 50) & (a % 2 == 0)]

array([70, 64, 82, 58, 96, 72, 92, 66, 66])

In [ ]:
# find all numbers not divisible by 7
a[~(a % 7 == 0)]

In [ ]:
##Broadcasting
#The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

#The smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [ ]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [ ]:
# diff shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [ ]:
#Broadcasting Rules
#1. Make the two arrays have the same number of dimensions.

#If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.
#2. Make each dimension of the two arrays the same size.

#If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
#If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

In [ ]:
# More examples

a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print(b)

print(a+b)

NameError: name 'np' is not defined

In [ ]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)

In [ ]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a + b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [ ]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)

print(a+b)

NameError: name 'np' is not defined

In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

print(a+b)

In [ ]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

In [ ]:
a = np.arange(10)
np.sin(a)

NameError: name 'np' is not defined

In [ ]:
# sigmoid
def sigmoid(array):
  return 1/(1 + np.exp(-(array)))


a = np.arange(100)

sigmoid(a)

NameError: name 'np' is not defined

In [ ]:
# mean squared error

actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)

In [ ]:
def mse(actual,predicted):
  return np.mean((actual - predicted)**2)

mse(actual,predicted)

In [ ]:
# binary cross entropy
np.mean((actual - predicted)**2)

In [ ]:
actual

In [ ]:
#Working with missing values

In [ ]:
a[~np.isnan(a)]

In [ ]:
#Plotting Graphs

In [ ]:
# plotting a 2D plot
# x = y
import matplotlib.pyplot as plt

x = np.linspace(-10,10,100)
y = x

plt.plot(x,y)

In [ ]:
# y = x^2
x = np.linspace(-10,10,100)
y = x**2

plt.plot(x,y)

In [ ]:
# y = sin(x)
x = np.linspace(-10,10,100)
y = np.sin(x)

plt.plot(x,y)

In [ ]:
# y = xlog(x)
x = np.linspace(-10,10,100)
y = x * np.log(x)

plt.plot(x,y)

In [ ]:
# sigmoid
x = np.linspace(-10,10,100)
y = 1/(1+np.exp(-x))

plt.plot(x,y)

NameError: name 'np' is not defined

In [ ]:
#Meshgrids