<a href="https://colab.research.google.com/github/Dakshak-Data/python_p/blob/main/NUMPY_TRICK3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

#Return a sorted copy of an array.

#https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code return numpynrray
import numpy as np
a = np.random.randint(1,100,15)
a

array([53, 32, 77, 50, 72, 29, 66, 42, 92,  2, 42, 71, 45, 85, 65])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[71, 29, 67, 59],
       [79, 74, 36, 14],
       [48, 33, 37, 88],
       [86,  9, 44, 14],
       [78, 59, 55, 46],
       [61, 81, 68, 19]])

In [4]:
np.sort(a)[::-1] #desc

array([92, 85, 77, 72, 71, 66, 65, 53, 50, 45, 42, 42, 32, 29,  2])

In [5]:
np.sort(b,axis=0)

array([[48,  9, 36, 14],
       [61, 29, 37, 14],
       [71, 33, 44, 19],
       [78, 59, 55, 46],
       [79, 74, 67, 59],
       [86, 81, 68, 88]])

In [6]:
#np.append
#The numpy.append() appends values along the mentioned axis at the end of the array

#https://numpy.org/doc/stable/reference/generated/numpy.append.html



In [7]:
# code
np.append(a,200)

array([ 53,  32,  77,  50,  72,  29,  66,  42,  92,   2,  42,  71,  45,
        85,  65, 200])

In [8]:
b

array([[71, 29, 67, 59],
       [79, 74, 36, 14],
       [48, 33, 37, 88],
       [86,  9, 44, 14],
       [78, 59, 55, 46],
       [61, 81, 68, 19]])

In [9]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[71.        , 29.        , 67.        , 59.        ,  0.4199415 ],
       [79.        , 74.        , 36.        , 14.        ,  0.1911073 ],
       [48.        , 33.        , 37.        , 88.        ,  0.28102196],
       [86.        ,  9.        , 44.        , 14.        ,  0.5847114 ],
       [78.        , 59.        , 55.        , 46.        ,  0.86672275],
       [61.        , 81.        , 68.        , 19.        ,  0.77514407]])

In [10]:
np.append(b,np.random((b.shape[0],1)),axis=1)

TypeError: 'module' object is not callable

In [ ]:
#np.concatenate
#numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

#https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

In [ ]:
np.concatenate((c,d),axis=0) #row concanate replacement of vstsck h stack

In [ ]:
np.concatenate((c,d),axis=1)

In [ ]:
#np.unique
#With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

#https://numpy.org/doc/stable/reference/generated/numpy.unique.html/


In [ ]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [ ]:
np.unique(e)

In [ ]:
#np.expand_dims
#With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

#https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [ ]:
# code  #we can convert 1d tp 2d
a.shape

In [11]:
np.expand_dims(a,axis=0).shape  #machine learning cnn image classification

(1, 15)

In [12]:
np.expand_dims(a,axis=1)

array([[53],
       [32],
       [77],
       [50],
       [72],
       [29],
       [66],
       [42],
       [92],
       [ 2],
       [42],
       [71],
       [45],
       [85],
       [65]])

In [13]:
#np.where
#The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

#https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [16]:
a

array([53, 32, 77, 50, 72, 29, 66, 42, 92,  2, 42, 71, 45, 85, 65])

In [17]:
# find all indices with value greater than 50 filter the array wiyh o\0
np.where(a>50)

(array([ 0,  2,  4,  6,  8, 11, 13, 14]),)

In [14]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0, 32,  0, 50,  0, 29,  0, 42,  0,  2, 42,  0, 45,  0,  0])

In [15]:
np.where(a%2 == 0,0,a)

array([53,  0, 77,  0,  0, 29,  0,  0,  0,  0,  0, 71, 45, 85, 65])

In [18]:
#he numpy.argmax() function returns indices of the max element of the array in a particular axis.

#https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [19]:
# code
a

array([53, 32, 77, 50, 72, 29, 66, 42, 92,  2, 42, 71, 45, 85, 65])

In [20]:
np.argmax(a)

np.int64(8)

In [21]:
b

array([[71, 29, 67, 59],
       [79, 74, 36, 14],
       [48, 33, 37, 88],
       [86,  9, 44, 14],
       [78, 59, 55, 46],
       [61, 81, 68, 19]])

In [22]:
np.argmax(b,axis=0)

array([3, 5, 5, 2])

In [24]:
np.argmax(b,axis=1)

array([0, 0, 3, 0, 0, 1])

In [23]:
# np.argmin
np.argmin(a)

np.int64(9)

In [25]:
#np.cumsum
#numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

#https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [26]:
a  #virat kholi  12+34+2+12+32+1+3+2 build in func

array([53, 32, 77, 50, 72, 29, 66, 42, 92,  2, 42, 71, 45, 85, 65])

In [27]:
np.cumsum(a)

array([ 53,  85, 162, 212, 284, 313, 379, 421, 513, 515, 557, 628, 673,
       758, 823])

In [28]:
b

array([[71, 29, 67, 59],
       [79, 74, 36, 14],
       [48, 33, 37, 88],
       [86,  9, 44, 14],
       [78, 59, 55, 46],
       [61, 81, 68, 19]])

In [ ]:
np.cumsum(b,axis=1)

In [29]:
np.cumsum(b)

array([  71,  100,  167,  226,  305,  379,  415,  429,  477,  510,  547,
        635,  721,  730,  774,  788,  866,  925,  980, 1026, 1087, 1168,
       1236, 1255])

In [30]:
# np.cumprod  virat 5*7*6*9*0*
np.cumprod(a)

array([                  53,                 1696,               130592,
                    6529600,            470131200,          13633804800,
               899831116800,       37792906905600,     3476947435315200,
           6953894870630400,   292063584566476800,  2289770430510301184,
       -7640795069293756416, -3831538310134988800,  9204426873159450624])

In [31]:
a

array([53, 32, 77, 50, 72, 29, 66, 42, 92,  2, 42, 71, 45, 85, 65])

In [32]:
#np.percentile
#numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

#https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [33]:
a

array([53, 32, 77, 50, 72, 29, 66, 42, 92,  2, 42, 71, 45, 85, 65])

In [34]:
np.percentile(a,50)

np.float64(53.0)

In [36]:
np.median(a)

np.float64(53.0)

In [35]:
#np.histogram
#Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

#https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [37]:
# code
a

array([53, 32, 77, 50, 72, 29, 66, 42, 92,  2, 42, 71, 45, 85, 65])

In [38]:
np.histogram(a,bins=[0,50,100])

(array([6, 9]), array([  0,  50, 100]))

In [39]:
#np.corrcoef
#Return Pearson product-moment correlation coefficients.

#https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html



In [40]:
salary = np.array([20000,40000,25000,35000,60000])  #shows the coreltion 1 salary and expereine increase
experience = np.array([1,3,2,4,2])                       #shows the coreltion 1 experience increase -1salary decrese
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [41]:
#np.isin
#With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

#https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [42]:
# code
a


array([53, 32, 77, 50, 72, 29, 66, 42, 92,  2, 42, 71, 45, 85, 65])

In [43]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([50])

In [44]:
#np.flip
#The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

#https://numpy.org/doc/stable/reference/generated/numpy.flip.html



In [45]:
# code
a

array([53, 32, 77, 50, 72, 29, 66, 42, 92,  2, 42, 71, 45, 85, 65])

In [ ]:
np.flip(a)

In [46]:
b

array([[71, 29, 67, 59],
       [79, 74, 36, 14],
       [48, 33, 37, 88],
       [86,  9, 44, 14],
       [78, 59, 55, 46],
       [61, 81, 68, 19]])

In [47]:
np.flip(b,axis=1)

array([[59, 67, 29, 71],
       [14, 36, 74, 79],
       [88, 37, 33, 48],
       [14, 44,  9, 86],
       [46, 55, 59, 78],
       [19, 68, 81, 61]])

In [50]:
#np.put
#The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

#https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [48]:
# code
a

array([53, 32, 77, 50, 72, 29, 66, 42, 92,  2, 42, 71, 45, 85, 65])

In [49]:
np.put(a,[0,1],[110,530]) #multiple new item change on exiting places perment change

In [51]:
#np.delete
#The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

#https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [53]:
# code
a

array([110, 530,  77,  50,  72,  29,  66,  42,  92,   2,  42,  71,  45,
        85,  65])

In [52]:
#Set functions
#np.union1d
#np.intersect1d
#np.setdiff1d
#np.setxor1d
#np.in1d

In [54]:
m = np.array([1,2,3,4,5]) ###best part is array me he result milega u getbresult in array onlg
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [55]:
np.intersect1d(m,n)

array([3, 4, 5])

In [56]:
np.setdiff1d(n,m)

array([6, 7])

In [58]:
np.setxor1d(m,n)  ##common remove

array([1, 2, 6, 7])

In [57]:
m[np.in1d(m,1)]

<ipython-input-57-3d5a78555eb5>:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

In [59]:
#np.clip
#numpy.clip() function is used to Clip (limit) the values in an array.

#https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [60]:
# code
a

array([110, 530,  77,  50,  72,  29,  66,  42,  92,   2,  42,  71,  45,
        85,  65])

In [61]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 50, 72, 29, 66, 42, 75, 25, 42, 71, 45, 75, 65])